name: CI/CD Pipeline for Django App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          python manage.py test

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/yourapp:${{ github.sha }} .

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push yourdockerhubusername/yourapp:${{ github.sha }}

