name: CI/CD Pipeline for Django App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          python manage.py test

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t omarhasni123/django-starter:${{ github.sha }} .

      # Step 6: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/django-starter:${{ github.sha }}

      # Step 8: Deploy to server using Ansible
      - name: Deploy to Server using Ansible
        uses: appleboy/ansible-playbook-action@v1
        with:
          playbook: deploy-django-app.yml
          extra_vars: |
            docker_tag=${{ github.sha }}

        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
